/*
 * this file contains ALL regular expressions that are used in atlp
 * it is intended to provide a way to "easily" add a language
 * DO NOT EDIT this file if you are not familiar with PCRE
 *
 * some placeholders get replaced while loading the regexps, these are:
 * !CHARNAME! - name of the character
 * !TRAINERS! - trainers in the conf-file, put together like this: Recupera|C'tego|...
 * 
 */

module logprocess.regexps;

import wx.wx;

enum AtlpLanguage
{
	all=0,	// same for every language 
	de, 	// german
	nl, 	// dutch
	fr, 	// french
	en,		// english
	
	totalsize 	// new entries before this one 
}

enum ArindalClass
{
	Common=0,
	Healer,
	Fighter,
	Mage,
	Secondary,
	Languages,
	
	totalsize
}

struct ArindalTrainer
{
	ArindalClass Class;
	int MaxRanks;
	char[] Message;
}


class RegExps
{
public:
	
public:
	char[][AtlpLanguage][char[]] regexps;
	//char[][char[]] SysMsgMap;
	int[char[]] TrnMsgMap;
	ArindalTrainer[char[]] Trainers;

	this()
	{
		/*
		 * arindal timestamp
		 * 
		 * <arts>: full timestamp
		 */
		auto reTimestamp = r"(?:(?P<arts>\d\d?/\d\d?/\d\d \d\d?:\d\d:\d\d(?:a|p) ))?+";
		regexps["TimestampSimple"][AtlpLanguage.de] = "^"~reTimestamp;
		regexps["TimestampFull"][AtlpLanguage.de] = r"^(?:(?P<month>\d\d?)/(?P<day>\d\d?)/(?P<year>\d\d) (?P<hour>\d\d?):(?P<minute>\d\d):(?P<second>\d\d)(?P<ap>a|p) )";
		/*
		 * find out if and how you killed a monster, and which one
		 * 
		 * <monster>: name of the monster
		 * <killtype>: (helped to) slaughter/dispatch/...
		 */
		regexps["MonsterKilltype"][AtlpLanguage.de] = "^" ~ reTimestamp ~ "Du hast (?:geholfen, )?ein(?:en?)? (?P<monster>.+) (?P<killtype>geschlachtet|erlegt|getötet|bezwungen|zu schlachten|zu erlegen|zu töten|zu bezwingen).$";
		/* the following is just an example */
		regexps["MonsterKilltype"][AtlpLanguage.en] = "^" ~ reTimestamp ~ "You (?P<killtype>slaughtered|dispatched|killed|vanquished|helped to slaughter|helped to dispatch|helped to kill|helped to vanquish) a (?P<monster>.+).$";
		
		/*
		 * fallen message
		 * 
		 * <monster>: name of the monster
		 */
		regexps["FallenMessage"][AtlpLanguage.de] = "^" ~ reTimestamp ~ r"Du bist durch (?:ein(?:en?)? )?(?P<monster>.+) gefallen.$";
		
		/*
		 * 1. prerequisite for the depart message
		 * 2. the actual depart, if message 1 came short before
		 * 
		 * <times>: depart no. - not used yet
		 */
		regexps["DepartMessage1"][AtlpLanguage.de] = "^" ~ reTimestamp ~ r"• Etwas zieht deinen Geist zurück in deinen Körper.$";
		regexps["DepartMessage2"][AtlpLanguage.de] = "^" ~ reTimestamp ~ r"Dein Geist hat deinen Körper (?P<times>[0-9]+) mal verlassen.$";

		/*
		 * /info self
		 * 
		 * <race>:	your race
		 * <sex>:	your sex
		 * <prof>:	your profession (wanderer, healer, fighter, mage)
		 */
		regexps["RaceSexProfession"][AtlpLanguage.de] = "^" ~ reTimestamp ~ "Du bist eine? (?P<race>[^,]+), bist (?P<sex>[^,]+), bist eine? (?P<prof>[^,]+), und (?:bist kein Mitglied eines offiziellen Clans|trägst das Symbol von (?P<clan>[a-zA-Z ]+))\\.$";
	 
		/*
		 * the greeting from your trainers reveals your title
		 * 
		 * <title>:	your title
		 */
		regexps["TitleMessage"][AtlpLanguage.de] = "^" ~ reTimestamp ~ "(?:!TRAINERS!) sagt, \"Hail, (?P<title>[a-zA-Z ]+) !CHARNAME!\\.";
		
		/*
		 * 1. prerequisite for the zodiac information
		 * 2. yapftzi (yet another...)
		 * 3. your soul's name and number
		 * 4. your zodiac sign
		 * 
		 * <soulname>: 	your soul's name
		 * <soulno>:	your soul's number
		 * <zodiac>:	your zodiac sign
		 */
		regexps["Zodiac1"][AtlpLanguage.de] = "^" ~ reTimestamp ~ "Soular sagt, \"Ah, hier bist du ja, !CHARNAME!\\.\"$";
		regexps["Zodiac2"][AtlpLanguage.de] = "^" ~ reTimestamp ~ "Soular sagt, \"Ich habe die gewünschten Daten\\.\"$";
		regexps["Zodiac3"][AtlpLanguage.de] = "^" ~ reTimestamp ~ "Soular sagt, \"Deine Seele \\((?P<soulname>[a-z]+)\\) kann numerisch als die Zahl (?P<soulno>[0-9]+) dargestellt werden\\.\"$";
		regexps["Zodiac4"][AtlpLanguage.de] = "^" ~ reTimestamp ~ "Soular sagt, \"Sie war unter dem Zeichen von (?P<zodiac>[a-zA-Zäöü ]+) geboren\\.\"$";
		 

		regexps["StartLogFindChar"][AtlpLanguage.de] = "^" ~ reTimestamp ~ "Willkommen (?:bei Arindal|zurück), (?<charname>[^!]++)!$";
		regexps["StartLog"][AtlpLanguage.de] = "^" ~ reTimestamp ~ "Willkommen (bei Arindal|zurück), !CHARNAME!!$";
		regexps["EndLog"][AtlpLanguage.de] = "^" ~ reTimestamp ~ r"\*\*\* Wir sind nicht mehr mit dem Arindal-Spielserver verbunden. \*\*\*$";
		 
		 /*
		  * trainer and system messages related to ranks
		  * SysMsgMap["message"] = "trainer"; - message = system message when gaining a rank
		  * TrnMsgMap["msg"] = number; - msg = progress message from trainer, number = approx. number of ranks
		  */
		regexps["SystemRankMessage"][AtlpLanguage.de] = "^" ~ reTimestamp ~ "•(?P<msg>(?:Du|Deine?) .+)$";
		regexps["TrainerProgressMessage"][AtlpLanguage.de] = "^" ~ reTimestamp ~ "(?P<trainer>!TRAINERS!) sagt, \"Hail,[a-zA-Z ]+!CHARNAME!\\. (?P<msg>.*)\"$";
		regexps["TrainerChosenMessage"][AtlpLanguage.de] = "^" ~ reTimestamp ~ "(?P<trainer>!TRAINERS!) sagt, \"Willkommen im Kreis meiner Schüler. Nun geh hinaus und lerne soviel du kannst bei der Ausübung unserer Kunst.\"$";
		regexps["YouShare"][AtlpLanguage.de] = "^" ~ reTimestamp ~ r"Du teilst (?:ab jetzt )?deine Erfahrung (?P<permanent>dauerhaft )?mit (?P<char>[a-zA-Z' ]+)\.$";
		regexps["YouDontShare"][AtlpLanguage.de] = "^" ~ reTimestamp ~ r"Du teilst nicht mehr deine Erfahrung mit (?P<char>[a-zA-Z' ]+)\.$";
		regexps["YouGetShared"][AtlpLanguage.de] = "^" ~ reTimestamp ~ r"(?P<char>[a-zA-Z' ]+) teilt Erfahrungen mit dir\.$";
		regexps["YouDontGetShared"][AtlpLanguage.de] = "^" ~ reTimestamp ~ r"(?P<char>[a-zA-Z' ]+) teilt nicht mehr Erfahrungen mit dir\.$";
		
		regexps["CollisseumChoose"][AtlpLanguage.de] = "^" ~ reTimestamp ~ "Roster fragt, \"So !CHARNAME!, wir nehmen (?P<monster>[a-zA-Zäöüß ]+) und davon (?P<number>[123]) Stück, richtig\\?\"$";
		regexps["CollisseumStartfight"][AtlpLanguage.de] = "^" ~ reTimestamp ~ "Arena master schreit, \"!CHARNAME! (?:ist der nächste. Plaziert eure Wetten|is up. Fighting against (?:one|two|three) [^.]+\\. Place your bets)!\"$";
		regexps["CollisseumWin"][AtlpLanguage.de] = "^" ~ reTimestamp ~ "Arena master schreit, \"!CHARNAME! gewinnt!\"$";
		regexps["CollisseumLose"][AtlpLanguage.de] = "^" ~ reTimestamp ~ "Arena master schreit, \"Das Biest hat gewonnen!\"$";
		  
		/* de */
		/* common */
		Trainers["Corpus"] = ArindalTrainer(ArindalClass.Common, 100, "Dein Körper fühlt sich etwas stärker an.");
		Trainers["Claro"] = ArindalTrainer(ArindalClass.Common, 0, "Deine mentalen Fähigkeiten scheinen sich erweitert zu haben.");
		Trainers["Esprit"] = ArindalTrainer(ArindalClass.Common, 0, "Deine geistige Ausdauer hat sich verbessert.");
		Trainers["Tandui"] = ArindalTrainer(ArindalClass.Common, 0, "Deine Studien bei der Verwertung von Zähnen scheinen sich auszuzahlen. Kchh!");
		Trainers["Pellia"] = ArindalTrainer(ArindalClass.Common, 0, "Deine Lehrstunden bei Pellia scheinen sich auszuzahlen.");
		Trainers["Skalio"] = ArindalTrainer(ArindalClass.Common, 0, "Deine Studien in der Verwertung von Schuppen scheinen sich auszuzahlen.");
		Trainers["Globinus"] = ArindalTrainer(ArindalClass.Common, 20, "Dein Studium des Blutablassens scheint sich auszuzahlen. ");
		Trainers["Oronar"] = ArindalTrainer(ArindalClass.Secondary, 0, "Du lernst, deine Werkzeuge besser instandzuhalten.");
		Trainers["Harnd Rite"] = ArindalTrainer(ArindalClass.Secondary, 10, "Du kannst nun besser schreiben.");
		Trainers["F'rritti"] = ArindalTrainer(ArindalClass.Secondary, 70, "Du meinst nun verborgene Wege besser finden zu können.");
		Trainers["Paad Finegrr"] = ArindalTrainer(ArindalClass.Secondary, 50, "Du meinst nun verborgene Wege besser finden zu können.");
		
		Trainers["Nauczyciel"] = ArindalTrainer(ArindalClass.Languages, 5, "Du bemerkst, dass du die Sprache der Azcatl etwas besser verstehst.");
		Trainers["Ka'nsah"] = ArindalTrainer(ArindalClass.Languages, 5, "Du bemerkst, dass du die Sprache der Drakh Nor etwas besser verstehst.");
		Trainers["Laerer"] = ArindalTrainer(ArindalClass.Languages, 5, "Du bemerkst, dass du die Sprache der Elithren etwas besser verstehst.");
		Trainers["Mwalimu"] = ArindalTrainer(ArindalClass.Languages, 5, "Du bemerkst, dass du die Sprache der Hamini etwas besser verstehst.");
		Trainers["Lareow"] = ArindalTrainer(ArindalClass.Languages, 5, "Du bemerkst, dass du die Sprache der Kyttyn etwas besser verstehst.");
		Trainers["Lärarinna"] = ArindalTrainer(ArindalClass.Languages, 5, "Du bemerkst, dass du die Sprache der Lepori etwas besser verstehst.");
		Trainers["Tanító"] = ArindalTrainer(ArindalClass.Languages, 5, "Du bemerkst, dass du die Sprache der Maqua etwas besser verstehst.");
		Trainers["Mësues"] = ArindalTrainer(ArindalClass.Languages, 5, "Du bemerkst, dass du die Sprache der Sirrush etwas besser verstehst.");
		Trainers["Uthisha"] = ArindalTrainer(ArindalClass.Languages, 5, "Du bemerkst, dass du die Sprache der Urdar etwas besser verstehst.");

		/* fighter */
		Trainers["Efficia"] = ArindalTrainer(ArindalClass.Fighter, 0, "Deine grundlegenden Kampftechniken scheinen wirksamer geworden zu sein.");
		Trainers["Stabilis"] = ArindalTrainer(ArindalClass.Fighter, 0, "Du bemerkst, dass sich deine Balance verbessert hat und sich schneller erholt.");
		Trainers["Battuo"] = ArindalTrainer(ArindalClass.Fighter, 0, "Du scheinst nun genauer zu treffen.");
		Trainers["Tutamen"] = ArindalTrainer(ArindalClass.Fighter, 0, "Du scheinst nun mehr einstecken zu können.");
		Trainers["C'tego"] = ArindalTrainer(ArindalClass.Fighter, 0, "Du kannst dich nun etwas besser verteidigen.");
		Trainers["Ponthera"] = ArindalTrainer(ArindalClass.Fighter, 0, "Du bemerkst, dass sich deine Balance verbessert hat.");
		Trainers["Resumiell"] = ArindalTrainer(ArindalClass.Fighter, 0, "Du erlangst nun deine Balance etwas schneller zurück.");
		Trainers["Laedo Ledo"] = ArindalTrainer(ArindalClass.Fighter, 0, "Du bemerkst, dass du nun mehr Schaden anrichten kannst.");
		Trainers["Genêze"] = ArindalTrainer(ArindalClass.Fighter, 50, "Du fühlst dich empfänglicher für Heilung.");
		/* healer */
		Trainers["Letifa"] = ArindalTrainer(ArindalClass.Healer, 0, "Du scheinst Verletzte, die dem Tode nahe sind, besser heilen zu können.");
		Trainers["Augea"] = ArindalTrainer(ArindalClass.Healer, 0, "Du scheinst nun mehr einstecken zu können.");
		Trainers["Recupera"] = ArindalTrainer(ArindalClass.Healer, 0, "Deine Geisteskräfte scheinen sich nun schneller zu erholen.");
		Trainers["Phasma"] = ArindalTrainer(ArindalClass.Healer, 10, "Du scheinst Geister jetzt besser verstehen zu können.");
		Trainers["Spritt"] = ArindalTrainer(ArindalClass.Healer, 0, "Deine geistigen Heilkräfte haben sich verbessert.");
		Trainers["Omnis"] = ArindalTrainer(ArindalClass.Healer, 0, "Deine Fähigkeiten als Heiler haben sich verbessert.");
		Trainers["Usa"] = ArindalTrainer(ArindalClass.Healer, 0, "Du bemerkst, dass du deine Heilkräfte länger einsetzen kannst.");
		Trainers["Citius"] = ArindalTrainer(ArindalClass.Healer, 0, "Du spürst, dass du andere schneller heilen kannst.");
		Trainers["Valens"] = ArindalTrainer(ArindalClass.Healer, 0, "Du scheinst dich nun selber besser mit dem Heilkristall heilen zu können.");
		Trainers["Salf'Haal"] = ArindalTrainer(ArindalClass.Healer, 30, "Du begreifst die Funktionsweise von Salynos Ring besser.");
		Trainers["Haya"] = ArindalTrainer(ArindalClass.Healer, 100, "Du kannst nun besser lokalisieren.");
		Trainers["Thola"] = ArindalTrainer(ArindalClass.Healer, 0, "Du kannst nun länger lokalisieren.");
		Trainers["Talál"] = ArindalTrainer(ArindalClass.Healer, 0, "Du kannst andere besser wahrnehmen.");
		Trainers["Distanse"] = ArindalTrainer(ArindalClass.Healer, 0, "Du scheinst nun etwas besser fernheilen zu können");
		Trainers["Zoya"] = ArindalTrainer(ArindalClass.Healer, 0, "Du bemerkst, dass sich deine Balance verbessert hat und sich schneller erholt.");
		Trainers["Tandui"] = ArindalTrainer(ArindalClass.Healer, 20, "Deine Studien bei der Verwertung von Zähnen scheinen sich auszuzahlen. Kchh!");
		Trainers["Tandua"] = ArindalTrainer(ArindalClass.Healer, 20, "Deine Studien bei der Verwertung von Zähnen scheinen sich auszuzahlen. Kchh!");

		TrnMsgMap["Schön, dich wiederzusehen."] = 10;
		TrnMsgMap["Deine Beharrlichkeit zahlt sich aus."] = 20;
		TrnMsgMap["Du machst gute Fortschritte."] = 30;
		TrnMsgMap["Du bist ein guter Schüler."] = 40;
		TrnMsgMap["Du bist einer meiner besseren Schüler."] = 50;
		TrnMsgMap["Du bist mir mit deinem Wissen dicht auf den Fersen."] = 100;
		TrnMsgMap["Es ist schwer, dir noch etwas Neues beizubringen."] = 150;
		TrnMsgMap["Es ist eine Herausforderung, dich zu unterrichten."] = 200;
		TrnMsgMap["Es gibt nicht mehr viel, was ich dir noch beibringen könnte."] = 250;
		TrnMsgMap["Dich zu unterrichten, hat auch mich viel gelehrt."] = 300;
		TrnMsgMap["Du hast ungeheure Fähigkeiten erreicht."] = 350;
		TrnMsgMap["Wir sind fast ebenbürtig."] = 400;
		TrnMsgMap["Du kannst wirklich stolz auf Deine Leistung sein."] = 450;
		TrnMsgMap["Du wirst langsam zu einem Meister unserer Kunst."] = 500;
		
		/* nl */
		/* fr */
	}
}


